### ISSUE TITLE
NumberFormatException in AgGithub

### ISSUE THREAD

**Issue by yegor256** [yegor256/wring#12]
```
java.lang.NumberFormatException: For input string: "13c4e6dfa8f8a3a8094185e385b2c546db3b6097"
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.lang.Integer.parseInt(Integer.java:580)
	at java.lang.Integer.parseInt(Integer.java:615)
	at io.wring.agents.github.AgGithub.push(AgGithub.java:142)
	at io.wring.agents.github.AgGithub.push(AgGithub.java:116)
	at io.wring.agents.JsonAgent.push(JsonAgent.java:86)
	at io.wring.agents.Cycle.log(Cycle.java:191)
	at io.wring.agents.Cycle.wrap(Cycle.java:162)
	at io.wring.agents.Cycle.process(Cycle.java:135)
	at io.wring.agents.Cycle.process(Cycle.java:106)
	at io.wring.agents.Cycle.run(Cycle.java:83)
```

**Comment by yegor256** [comment]
@rultor release, tag is `0.8.4`
