### ISSUE TITLE
IllegalArgumentException: subject ignored

### ISSUE THREAD

**Issue by yegor256** [yegor256/wring#20]
```
2016-03-21T23:08Z java.lang.IllegalArgumentException: subject ignored: {"title":"...","url":"https://api.github.com/repos/teamed/xxx/commits/1068878fb76440ec21837fd7bf42ea287dc4c86f","latest_comment_url":"https://api.github.com/repos/teamed/xxx/comments/16792475","type":"Commit"}
	at io.wring.agents.github.AgGithub.push(AgGithub.java:146)
	at io.wring.agents.github.AgGithub.push(AgGithub.java:118)
	at io.wring.agents.JsonAgent.push(JsonAgent.java:86)
	at io.wring.agents.Exec.log(Exec.java:144)
	at io.wring.agents.Exec.body(Exec.java:118)
	at io.wring.agents.Exec.run(Exec.java:84)
	at io.wring.agents.Cycle.process(Cycle.java:104)
	at io.wring.agents.Cycle.run(Cycle.java:77)
	at com.jcabi.log.VerboseRunnable.run(VerboseRunnable.java:198)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at com.jcabi.log.VerboseThreads$Wrap.run(VerboseThreads.java:220)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by yegor256** [comment]
@rultor release, tag is `0.12.3`
