### ISSUE TITLE
Internal Application Error when adding empty Pipe

### ISSUE THREAD

**Issue by amihaiemil** [yegor256/wring#22]
If I try to add an empty Pipe, I get the following internal error:
```
java.lang.IllegalStateException: [POST http://www.wring.io/pipe-add] failed in 33ms: Cannot auto-detect encoding, not enough chars
	at org.takes.facets.fallback.TkFallback.error(TkFallback.java:233)
	at org.takes.facets.fallback.TkFallback.route(TkFallback.java:112)
	at org.takes.facets.fallback.TkFallback.access$000(TkFallback.java:54)
	at org.takes.facets.fallback.TkFallback$1.act(TkFallback.java:66)
	at org.takes.tk.TkWrap.act(TkWrap.java:61)
	at org.takes.tk.TkWrap.act(TkWrap.java:61)
	at org.takes.facets.flash.TkFlash.act(TkFlash.java:108)
	at org.takes.tk.TkGzip$1.act(TkGzip.java:58)
	at org.takes.tk.TkWrap.act(TkWrap.java:61)
	at org.takes.tk.TkMeasured$1.act(TkMeasured.java:67)
	at org.takes.tk.TkWrap.act(TkWrap.java:61)
	at org.takes.tk.TkVersioned$1.act(TkVersioned.java:72)
	at org.takes.tk.TkWrap.act(TkWrap.java:61)
	at org.takes.tk.TkWithHeaders$1.act(TkWithHeaders.java:71)
	at org.takes.tk.TkWrap.act(TkWrap.java:61)
	at org.takes.tk.TkWrap.act(TkWrap.java:61)
	at org.takes.http.BkBasic.print(BkBasic.java:100)
	at org.takes.http.BkBasic.accept(BkBasic.java:78)
	at org.takes.http.BkSafe$1.accept(BkSafe.java:51)
	at org.takes.http.BkWrap.accept(BkWrap.java:52)
	at org.takes.http.BkTimeable.accept(BkTimeable.java:89)
	at org.takes.http.BkParallel$1$1.run(BkParallel.java:89)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: javax.json.JsonException: Cannot auto-detect encoding, not enough chars
	at org.glassfish.json.UnicodeDetectingInputStream.detectEncoding(UnicodeDetectingInputStream.java:131)
	at org.glassfish.json.UnicodeDetectingInputStream.(UnicodeDetectingInputStream.java:76)
	at org.glassfish.json.JsonParserImpl.(JsonParserImpl.java:76)
	at org.glassfish.json.JsonReaderImpl.(JsonReaderImpl.java:68)
	at org.glassfish.json.JsonProviderImpl.createReader(JsonProviderImpl.java:131)
	at javax.json.Json.createReader(Json.java:220)
	at io.wring.dynamo.DyPipes.add(DyPipes.java:96)
	at io.wring.tk.TkPipeAdd.act(TkPipeAdd.java:65)
	at org.takes.facets.fork.FkRegex$1.act(FkRegex.java:152)
	at org.takes.facets.fork.FkRegex.route(FkRegex.java:189)
	at org.takes.facets.fork.FkChain.route(FkChain.java:75)
	at org.takes.facets.fork.TkFork.act(TkFork.java:100)
	at org.takes.facets.auth.TkSecure.act(TkSecure.java:86)
	at org.takes.facets.fork.FkAuthenticated.route(FkAuthenticated.java:82)
	at org.takes.facets.fork.FkChain.route(FkChain.java:75)
	at org.takes.facets.fork.TkFork.act(TkFork.java:100)
	at org.takes.facets.forward.TkForward.act(TkForward.java:68)
	at org.takes.facets.fork.FkFixed$1.route(FkFixed.java:56)
	at org.takes.facets.fork.FkWrap.route(FkWrap.java:61)
	at org.takes.facets.fork.FkChain.route(FkChain.java:75)
	at org.takes.facets.fork.TkFork.act(TkFork.java:100)
	at org.takes.facets.auth.TkAuth.act(TkAuth.java:109)
	at org.takes.facets.auth.TkAuth.act(TkAuth.java:89)
	at org.takes.tk.TkWrap.act(TkWrap.java:61)
	at org.takes.facets.fallback.TkFallback.route(TkFallback.java:85)
	... 23 more
```

**Comment by amihaiemil** [comment]
An exception is thrown also if the JSON is not properly formater. I'll make a PR with a fix when I have time.

**Comment by amihaiemil** [comment]
@yegor256 I created PR #26 for this issue.
