### ISSUE TITLE
Illegal group reference in XePrint

### ISSUE THREAD

**Issue by yegor256** [yegor256/wring#33]
```
Caused by: java.lang.IllegalArgumentException: Illegal group reference
	at java.util.regex.Matcher.appendReplacement(Matcher.java:857)
	at io.wring.model.XePrint.text(XePrint.java:73)
	at io.wring.tk.TkEvents.source(TkEvents.java:106)
	at org.takes.rs.xe.XeTransform$1.next(XeTransform.java:101)
	at org.takes.rs.xe.XeTransform$1.next(XeTransform.java:93)
	at org.takes.rs.xe.XeChain$1.toXembly(XeChain.java:62)
	at org.takes.rs.xe.XeWrap.toXembly(XeWrap.java:57)
	at org.takes.rs.xe.XeChain$1.toXembly(XeChain.java:63)
	at org.takes.rs.xe.XeWrap.toXembly(XeWrap.java:57)
	at org.takes.rs.xe.XeAppend$1.toXembly(XeAppend.java:73)
	at org.takes.rs.xe.XeWrap.toXembly(XeWrap.java:57)
	at org.takes.rs.xe.XeChain$1.toXembly(XeChain.java:63)
	at org.takes.rs.xe.XeWrap.toXembly(XeWrap.java:57)
```

**Comment by yegor256** [comment]
@rultor release, tag is `0.14.1`
