### ISSUE TITLE
IllegalArgumentException: Event with title "Internal error (java.lang.NullPointerException): null by 1.0-SNAPSHOT" not found

### ISSUE THREAD

**Issue by yegor256** [yegor256/wring#37]
```
IllegalArgumentException: Event with title "Internal error (java.lang.NullPointerException): null by 1.0-SNAPSHOT" not found
    at io.wring.dynamo.DyEvents.event(DyEvents.java:160)
    at io.wring.agents.IgnoreEvents.event(IgnoreEvents.java:112)
    at io.wring.agents.BoostEvents.post(BoostEvents.java:102)
    at io.wring.agents.Exec.run(Exec.java:106)
    at io.wring.agents.Cycle.lambda$process$2(Cycle.java:114)
...
(23 additional frame(s) were not displayed)

IOException: java.lang.IllegalArgumentException: Event with title "Internal error (java.lang.NullPointerException): null by 1.0-SNAPSHOT" not found
    at org.cactoos.func.IoCheckedFunc.apply(IoCheckedFunc.java:74)
    at org.cactoos.func.UncheckedFunc.apply(UncheckedFunc.java:59)
    at io.wring.agents.Cycle.process(Cycle.java:117)
    at io.wring.agents.Cycle.exec(Cycle.java:75)
    at io.wring.agents.Cycle.exec(Cycle.java:56)
...
(15 additional frame(s) were not displayed)

UncheckedIOException: java.io.IOException: java.lang.IllegalArgumentException: Event with title "Internal error (java.lang.NullPointerException): null by 1.0-SNAPSHOT" not found
    at org.cactoos.func.UncheckedFunc.apply(UncheckedFunc.java:61)
    at io.wring.agents.Cycle.process(Cycle.java:117)
    at io.wring.agents.Cycle.exec(Cycle.java:75)
    at io.wring.agents.Cycle.exec(Cycle.java:56)
    at org.cactoos.func.FuncOf.lambda$new$3(FuncOf.java:88)
...
(14 additional frame(s) were not displayed)
```

**Comment by yegor256** [comment]
fixed

**Comment by 0crat** [comment]
Oops! Job `gh:yegor256/wring#37` was not in scope
