### ISSUE TITLE
NPE in Exec

### ISSUE THREAD

**Issue by yegor256** [yegor256/wring#38]
```
NullPointerException: None
    at io.wring.agents.Exec.run(Exec.java:96)
    at io.wring.agents.Cycle.lambda$process$2(Cycle.java:114)
    at org.cactoos.func.FuncOf.lambda$new$3(FuncOf.java:88)
    at org.cactoos.func.FuncOf.apply(FuncOf.java:104)
    at org.cactoos.func.FuncWithFallback.apply(FuncWithFallback.java:274)
...
(20 additional frame(s) were not displayed)

IOException: java.lang.NullPointerException
    at org.cactoos.func.IoCheckedFunc.apply(IoCheckedFunc.java:74)
    at org.cactoos.func.UncheckedFunc.apply(UncheckedFunc.java:59)
    at io.wring.agents.Cycle.process(Cycle.java:117)
    at io.wring.agents.Cycle.exec(Cycle.java:75)
    at io.wring.agents.Cycle.exec(Cycle.java:56)
...
(15 additional frame(s) were not displayed)

UncheckedIOException: java.io.IOException: java.lang.NullPointerException
    at org.cactoos.func.UncheckedFunc.apply(UncheckedFunc.java:61)
    at io.wring.agents.Cycle.process(Cycle.java:117)
    at io.wring.agents.Cycle.exec(Cycle.java:75)
    at io.wring.agents.Cycle.exec(Cycle.java:56)
    at org.cactoos.func.FuncOf.lambda$new$3(FuncOf.java:88)
...
(14 additional frame(s) were not displayed)
```

**Comment by yegor256** [comment]
fixed

**Comment by 0crat** [comment]
Oops! Job `gh:yegor256/wring#38` was not in scope
