### ISSUE TITLE
NPE in JsonAgent

### ISSUE THREAD

**Issue by yegor256** [yegor256/wring#39]
```
java.lang.NullPointerException: null
    at org.glassfish.json.JsonObjectBuilderImpl$JsonObjectImpl.getString(JsonObjectBuilderImpl.java:199)
    at io.wring.agents.JsonAgent.agent(JsonAgent.java:94)
    at io.wring.agents.JsonAgent.toString(JsonAgent.java:81)
    at io.wring.agents.Exec.run(Exec.java:85)
    at io.wring.agents.Cycle.lambda$process$2(Cycle.java:114)
    at org.cactoos.func.FuncOf.lambda$new$3(FuncOf.java:88)
    at org.cactoos.func.FuncOf.apply(FuncOf.java:104)
    at org.cactoos.func.FuncWithFallback.apply(FuncWithFallback.java:274)
    at org.cactoos.func.IoCheckedFunc.apply(IoCheckedFunc.java:66)
    at org.cactoos.func.UncheckedFunc.apply(UncheckedFunc.java:59)
    at io.wring.agents.Cycle.process(Cycle.java:117)
    at io.wring.agents.Cycle.exec(Cycle.java:75)
    at io.wring.agents.Cycle.exec(Cycle.java:56)
    at org.cactoos.func.FuncOf.lambda$new$3(FuncOf.java:88)
    at org.cactoos.func.FuncOf.apply(FuncOf.java:104)
    at org.cactoos.func.FuncWithFallback.apply(FuncWithFallback.java:266)
    at org.cactoos.func.IoCheckedFunc.apply(IoCheckedFunc.java:66)
    at org.cactoos.func.UncheckedFunc.apply(UncheckedFunc.java:59)
    at org.cactoos.func.RunnableOf.run(RunnableOf.java:89)
    at com.jcabi.log.VerboseRunnable.run(VerboseRunnable.java:198)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at com.jcabi.log.VerboseThreads$Wrap.run(VerboseThreads.java:220)
    at java.lang.Thread.run(Thread.java:745)
java.io.IOException: java.lang.NullPointerException
    at org.cactoos.func.IoCheckedFunc.apply(IoCheckedFunc.java:74)
    at org.cactoos.func.UncheckedFunc.apply(UncheckedFunc.java:59)
    at io.wring.agents.Cycle.process(Cycle.java:117)
    at io.wring.agents.Cycle.exec(Cycle.java:75)
    at io.wring.agents.Cycle.exec(Cycle.java:56)
    at org.cactoos.func.FuncOf.lambda$new$3(FuncOf.java:88)
    at org.cactoos.func.FuncOf.apply(FuncOf.java:104)
    at org.cactoos.func.FuncWithFallback.apply(FuncWithFallback.java:266)
    at org.cactoos.func.IoCheckedFunc.apply(IoCheckedFunc.java:66)
    at org.cactoos.func.UncheckedFunc.apply(UncheckedFunc.java:59)
    at org.cactoos.func.RunnableOf.run(RunnableOf.java:89)
    at com.jcabi.log.VerboseRunnable.run(VerboseRunnable.java:198)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at com.jcabi.log.VerboseThreads$Wrap.run(VerboseThreads.java:220)
    at java.lang.Thread.run(Thread.java:745)
java.io.UncheckedIOException: java.io.IOException: java.lang.NullPointerException
    at org.cactoos.func.UncheckedFunc.apply(UncheckedFunc.java:61)
    at io.wring.agents.Cycle.process(Cycle.java:117)
    at io.wring.agents.Cycle.exec(Cycle.java:75)
    at io.wring.agents.Cycle.exec(Cycle.java:56)
    at org.cactoos.func.FuncOf.lambda$new$3(FuncOf.java:88)
    at org.cactoos.func.FuncOf.apply(FuncOf.java:104)
    at org.cactoos.func.FuncWithFallback.apply(FuncWithFallback.java:266)
    at org.cactoos.func.IoCheckedFunc.apply(IoCheckedFunc.java:66)
    at org.cactoos.func.UncheckedFunc.apply(UncheckedFunc.java:59)
    at org.cactoos.func.RunnableOf.run(RunnableOf.java:89)
    at com.jcabi.log.VerboseRunnable.run(VerboseRunnable.java:198)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at com.jcabi.log.VerboseThreads$Wrap.run(VerboseThreads.java:220)
    at java.lang.Thread.run(Thread.java:745)
```

**Comment by yegor256** [comment]
@rultor release, tag is `0.15`

**Comment by 0crat** [comment]
Oops! Job `gh:yegor256/wring#39` was not in scope
