### ISSUE TITLE
AssertionError: HTTP response status is not equal to 200:

### ISSUE THREAD

**Issue by yegor256** [yegor256/wring#42]
https://sentry.io/zerocracy/wring/issues/334675232/

```
AssertionError: HTTP response status is not equal to 200:
404 Not Found [https://api.github.com/repos/zerocracy/farm/issues/242/comments]
Server: GitHub.com
Date: Thu, 24 Aug 2017 06:27:28 GMT
Content-Type: application/json; charset=utf-8
Transfer-Encoding: chunked
Status: 404 Not Found
X-RateLimit-Limit: 5000
X-RateLimit-Remaining: 4961
X-RateLimit-Reset: 1503558943
X-OAuth-Scopes: notifications
X-Accepted-OAuth-Scopes: repo
X-GitHub-Media-Type: github.v3
Access-Control-Expose-Headers: ETag, Link, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval
Access-Control-Allow-Origin: *
Content-Security-Policy: default-src 'none'
Strict-Transport-Security: max-age=31536000; includeSubdomains; preload
X-Content-Type-Options: nosniff
X-Frame-Options: deny
X-XSS-Protection: 1; mode=block
X-Runtime-Rack: 0.027776
X-GitHub-Request-Id: D921:22E16:CB3483:1A14D63:599E71D0

{"message":"Not Found","documentation_url":"https://developer.github.com/v3"}
Expected: HTTP response with status 200
     but: was <404 Not Found [https://api.github.com/repos/zerocracy/farm/issues/242/comments]
Server: GitHub.com
Date: Thu, 24 Aug 2017 06:27:28 GMT
Content-Type: application/json; charset=utf-8
Transfer-Encoding: chunked
Status: 404 Not Found
X-RateLimit-Limit: 5000
X-RateLimit-Remaining: 4961
X-RateLimit-Reset: 1503558943
X-OAuth-Scopes: notifications
X-Accepted-OAuth-Scopes: repo
X-GitHub-Media-Type: github.v3
Access-Control-Expose-Headers: ETag, Link, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval
Access-Control-Allow-Origin: *
Content-Security-Policy: default-src 'none'
Strict-Transport-Security: max-age=31536000; includeSubdomains; preload
X-Content-Type-Options: nosniff
X-Frame-Options: deny
X-XSS-Protection: 1; mode=block
X-Runtime-Rack: 0.027776
X-GitHub-Request-Id: D921:22E16:CB3483:1A14D63:599E71D0

{"message":"Not Found","documentation_url":"https://developer.github.com/v3"}>
    at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
    at com.jcabi.http.response.RestResponse.assertStatus(RestResponse.java:111)
    at com.jcabi.github.RtValuePagination$Items.fetch(RtValuePagination.java:193)
    at com.jcabi.github.RtValuePagination$Items.hasNext(RtValuePagination.java:179)
    at com.jcabi.github.Smarts$1.hasNext(Smarts.java:87)
...
(37 additional frame(s) were not displayed)

HTTP response status is not equal to 200:
404 Not Found [https://api.github.com/repos/zerocracy/farm/issues/242/comments]
Server: GitHub.com
Date: Thu, 24 Aug 2017 06:27:28 GMT
Content-Type: application/json; charset=utf-8
Transfer-Encoding: chunked
Status: 404 Not Found
X-RateLimit-Limit: 5000
X-RateLimit-Remaining: 4961
X-RateLimit-Reset: 1503558943
X-OAuth-Scopes: notifications
X-Accepted-OAuth-Scopes: repo
X-GitHub-Media-Type: github.v3
Access-Control-Expose-Headers: ETag, Link, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval
Access-Control-Allow-Origin: *
Content-Security-Policy: default-src 'none'
Strict-Transport-Security: max-age=31536000; includeSubdomains; preload
X-Content-Type-Options: nosniff
X-Frame-Options: deny
X-XSS-Protection: 1; mode=block
X-Runtime-Rack: 0.027776
X-GitHub-Request-Id: D921:22E16:CB3483:1A14D63:599E71D0

{"message":"Not Found","documentation_url":"https://developer....
```

**Comment by 0crat** [comment]
Job `gh:yegor256/wring#42` assigned to @yegor256, please go ahead ([policy](http://datum.zerocracy.com/pages/policy.html)).

**Comment by 0crat** [comment]
+15 points just awarded to @yegor256, total is [+2310](http://www.0crat.com/u/yegor256).

**Comment by 0crat** [comment]
@yegor256 this job was assigned to you 8 days ago.
It will be taken away from you after 10 days from start (this is our policy).

**Comment by 0crat** [comment]
@yegor256 resigned from `gh:yegor256/wring#42`, please stop working.

**Comment by 0crat** [comment]
Oops! Job `gh:yegor256/wring#42` is not assigned to anyone.

**Comment by yegor256** [comment]
don't see it anymore

**Comment by 0crat** [comment]
The job is not in WBS, won't close the order

**Comment by 0crat** [comment]
The job [#42](https://github.com/yegor256/wring/issues/42) is now out of scope
