### ISSUE TITLE
UncheckedIOException: io.wring.agents.Agent$UserException: Element 'boost' must be an array

### ISSUE THREAD

**Issue by yegor256** [yegor256/wring#47]
https://sentry.io/zerocracy/wring/issues/363038806/

```
UserException: Element 'boost' must be an array
    at io.wring.agents.BoostEvents.pattern(BoostEvents.java:134)
    at io.wring.agents.BoostEvents.<init>(BoostEvents.java:73)
    at io.wring.agents.Cycle.lambda$exec$2(Cycle.java:89)
    at org.cactoos.func.FuncOf.lambda$new$3(FuncOf.java:88)
    at org.cactoos.func.FuncOf.apply(FuncOf.java:104)
...
(18 additional frame(s) were not displayed)

UncheckedIOException: io.wring.agents.Agent$UserException: Element 'boost' must be an array
    at org.cactoos.func.UncheckedFunc.apply(UncheckedFunc.java:61)
    at io.wring.agents.Cycle.exec(Cycle.java:96)
    at io.wring.agents.Cycle.exec(Cycle.java:54)
    at org.cactoos.func.FuncOf.lambda$new$3(FuncOf.java:88)
    at org.cactoos.func.FuncOf.apply(FuncOf.java:104)
...
(11 additional frame(s) were not displayed)

io.wring.agents.Agent$UserException: Element 'boost' must be an array
```

**Comment by yegor256** [comment]
Full:

```
io.wring.agents.UserException: Element 'boost' must be an array
    at io.wring.agents.BoostEvents.pattern(BoostEvents.java:134)
    at io.wring.agents.BoostEvents.<init>(BoostEvents.java:73)
    at io.wring.agents.Cycle.lambda$exec$2(Cycle.java:89)
    at org.cactoos.func.FuncOf.lambda$new$3(FuncOf.java:88)
    at org.cactoos.func.FuncOf.apply(FuncOf.java:104)
    at org.cactoos.func.FuncWithFallback.apply(FuncWithFallback.java:307)
    at org.cactoos.func.IoCheckedFunc.apply(IoCheckedFunc.java:66)
    at org.cactoos.func.UncheckedFunc.apply(UncheckedFunc.java:59)
    at io.wring.agents.Cycle.exec(Cycle.java:96)
    at io.wring.agents.Cycle.exec(Cycle.java:54)
    at org.cactoos.func.FuncOf.lambda$new$3(FuncOf.java:88)
    at org.cactoos.func.FuncOf.apply(FuncOf.java:104)
    at org.cactoos.func.FuncWithFallback.apply(FuncWithFallback.java:299)
    at org.cactoos.func.IoCheckedFunc.apply(IoCheckedFunc.java:66)
    at org.cactoos.func.UncheckedFunc.apply(UncheckedFunc.java:59)
    at org.cactoos.func.RunnableOf.run(RunnableOf.java:89)
    at com.jcabi.log.VerboseRunnable.run(VerboseRunnable.java:198)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
    at com.jcabi.log.VerboseThreads$Wrap.run(VerboseThreads.java:220)
    at java.lang.Thread.run(Thread.java:748)
java.io.UncheckedIOException: io.wring.agents.Agent$UserException: Element 'boost' must be an array
    at org.cactoos.func.UncheckedFunc.apply(UncheckedFunc.java:61)
    at io.wring.agents.Cycle.exec(Cycle.java:96)
    at io.wring.agents.Cycle.exec(Cycle.java:54)
    at org.cactoos.func.FuncOf.lambda$new$3(FuncOf.java:88)
    at org.cactoos.func.FuncOf.apply(FuncOf.java:104)
    at org.cactoos.func.FuncWithFallback.apply(FuncWithFallback.java:299)
    at org.cactoos.func.IoCheckedFunc.apply(IoCheckedFunc.java:66)
    at org.cactoos.func.UncheckedFunc.apply(UncheckedFunc.java:59)
    at org.cactoos.func.RunnableOf.run(RunnableOf.java:89)
    at com.jcabi.log.VerboseRunnable.run(VerboseRunnable.java:198)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
    at com.jcabi.log.VerboseThreads$Wrap.run(VerboseThreads.java:220)
    at java.lang.Thread.run(Thread.java:748)

```

**Comment by yegor256** [comment]
@rultor release, tag is `0.17.6`

**Comment by 0crat** [comment]
The job is not in WBS, won't close the order
