### ISSUE TITLE
javax.json.stream.JsonParsingException for valid regex

### ISSUE THREAD

**Issue by g4s8** [yegor256/wring#52]
I'm trying to add some ignore rules with regex, according to [blog post](http://www.yegor256.com/2016/03/15/wring-dispatcher-github-notifications.html) I've wrapped it in `/` chars:
```json
{
  "class": "io.wring.agents.github.AgGithub",
  "token": "some-token",
  "ignore": [
    "/@[a-z0-9\\-]\\s+This is what I know about this job/"
  ]
}
```
it was accepted as a new pipe, but now I'm receiving errors in my inbox instead of events:
```
javax.json.stream.JsonParsingException: Unexpected char 45 at (line no=5, column no=16, offset=136)
	at org.glassfish.json.JsonTokenizer.unexpectedChar(JsonTokenizer.java:601)
	at org.glassfish.json.JsonTokenizer.unescape(JsonTokenizer.java:231)
	at org.glassfish.json.JsonTokenizer.readString(JsonTokenizer.java:184)
	at org.glassfish.json.JsonTokenizer.nextToken(JsonTokenizer.java:379)
	at org.glassfish.json.JsonParserImpl$ArrayContext.getNextEvent(JsonParserImpl.java:518)
	at org.glassfish.json.JsonParserImpl.next(JsonParserImpl.java:363)
	at org.glassfish.json.JsonParserImpl.getArray(JsonParserImpl.java:322)
	at org.glassfish.json.JsonParserImpl.getValue(JsonParserImpl.java:180)
	at org.glassfish.json.JsonParserImpl.getObject(JsonParserImpl.java:339)
	at org.glassfish.json.JsonParserImpl.getObject(JsonParserImpl.java:173)
	at org.glassfish.json.JsonReaderImpl.readObject(JsonReaderImpl.java:112)
	at io.wring.agents.Cycle.lambda$exec$0(Cycle.java:80)
	at org.cactoos.func.FuncWithFallback.apply(FuncWithFallback.java:84)
	at org.cactoos.func.UncheckedFunc.lambda$apply$0(UncheckedFunc.java:58)
	at org.cactoos.scalar.IoCheckedScalar.value(IoCheckedScalar.java:70)
	at org.cactoos.scalar.UncheckedScalar.value(UncheckedScalar.java:58)
	at org.cactoos.func.UncheckedFunc.apply(UncheckedFunc.java:59)
	at io.wring.agents.Cycle.exec(Cycle.java:99)
	at io.wring.agents.Cycle.exec(Cycle.java:54)
	at org.cactoos.func.FuncOf.lambda$new$3(FuncOf.java:88)
	at org.cactoos.func.FuncOf.apply(FuncOf.java:104)
	at org.cactoos.func.FuncWithFallback.apply(FuncWithFallback.java:84)
	at org.cactoos.func.UncheckedFunc.lambda$apply$0(UncheckedFunc.java:58)
	at org.cactoos.scalar.IoCheckedScalar.value(IoCheckedScalar.java:70)
	at org.cactoos.scalar.UncheckedScalar.value(UncheckedScalar.java:58)
	at org.cactoos.func.UncheckedFunc.apply(UncheckedFunc.java:59)
	at org.cactoos.func.RunnableOf.run(RunnableOf.java:89)
	at com.jcabi.log.VerboseRunnable.run(VerboseRunnable.java:198)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at com.jcabi.log.VerboseThreads$Wrap.run(VerboseThreads.java:220)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by yegor256** [comment]
@g4s8 weird... can you please post full stacktrace from your inbox?

**Comment by g4s8** [comment]
@yegor256 updated stakctrace https://github.com/yegor256/wring/issues/52#issue-305463828

**Comment by yegor256** [comment]
@g4s8 I believe it's reproduced and fixed in de7e049

**Comment by yegor256** [comment]
@rultor release, tag is `0.19.1`

**Comment by g4s8** [comment]
@yegor256 thanks

**Comment by 0crat** [comment]
The job is not in WBS, won't close the order
