### ISSUE TITLE
NullPointerException

### ISSUE THREAD

**Issue by yegor256** [yegor256/wring#53]
https://sentry.io/zerocracy/wring-bx/issues/493024338/

```
NullPointerException: None
    at io.wring.agents.JsonAgent.agent(JsonAgent.java:95)
    at io.wring.agents.JsonAgent.name(JsonAgent.java:81)
    at io.wring.agents.Exec.lambda$run$0(Exec.java:97)
    at org.cactoos.func.FuncWithFallback.apply(FuncWithFallback.java:84)
    at org.cactoos.func.UncheckedFunc.lambda$apply$0(UncheckedFunc.java:58)
...
(27 additional frame(s) were not displayed)
```

**Comment by 0crat** [comment]
The job is not in WBS, won't close the order
