### ISSUE TITLE
NullPointerException

### ISSUE THREAD

**Issue by yegor256** [yegor256/wring#54]
https://sentry.io/zerocracy/wring-bx/issues/493024339/

```
NullPointerException: None
    at io.wring.agents.IgnoreEvents.pattern(IgnoreEvents.java:151)
    at io.wring.agents.IgnoreEvents.lambda$new$0(IgnoreEvents.java:74)
    at org.cactoos.scalar.SolidScalar.lambda$new$0(SolidScalar.java:55)
    at org.cactoos.func.StickyFunc.lambda$new$0(StickyFunc.java:72)
    at org.cactoos.func.StickyBiFunc.apply(StickyBiFunc.java:95)
...
(30 additional frame(s) were not displayed)
```

**Comment by 0crat** [comment]
The job is not in WBS, won't close the order
