### ISSUE TITLE
all threads are dead

### ISSUE THREAD

**Issue by yegor256** [yegor256/wring#57]
I see this in production:

```
2018-04-04T16:42:38.412500+00:00 app[web.1]: BUILD com.jcabi.log.VerboseRunnable: swallowed exception: java.lang.IllegalStateException: java.util.concurrent.TimeoutException
2018-04-04T16:42:38.412520+00:00 app[web.1]: 	at io.wring.agents.Routine.run(Routine.java:129)
2018-04-04T16:42:38.412522+00:00 app[web.1]: 	at com.jcabi.log.VerboseRunnable.run(VerboseRunnable.java:198)
2018-04-04T16:42:38.412524+00:00 app[web.1]: 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
2018-04-04T16:42:38.412526+00:00 app[web.1]: 	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
2018-04-04T16:42:38.412531+00:00 app[web.1]: 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
2018-04-04T16:42:38.412533+00:00 app[web.1]: 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
2018-04-04T16:42:38.412535+00:00 app[web.1]: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
2018-04-04T16:42:38.412536+00:00 app[web.1]: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
2018-04-04T16:42:38.412538+00:00 app[web.1]: 	at com.jcabi.log.VerboseThreads$Wrap.run(VerboseThreads.java:220)
2018-04-04T16:42:38.412540+00:00 app[web.1]: 	at java.lang.Thread.run(Thread.java:748)
2018-04-04T16:42:38.412541+00:00 app[web.1]: Caused by: java.util.concurrent.TimeoutException
2018-04-04T16:42:38.412543+00:00 app[web.1]: 	at java.util.concurrent.FutureTask.get(FutureTask.java:205)
2018-04-04T16:42:38.412545+00:00 app[web.1]: 	at io.wring.agents.Routine.run(Routine.java:126)
2018-04-04T16:42:38.412547+00:00 app[web.1]: 	... 9 more
2018-04-04T16:42:38.412549+00:00 app[web.1]:
```

Then, I have to restart the server in order to let the threads be active again. Looks like we're running out of them after some time (2-5 days).

**Comment by 0crat** [comment]
Job [#57](https://github.com/yegor256/wring/issues/57) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) everybody who has role `DEV` are banned at this job; I won't be able to assign anyone automatically; consider assigning someone manually or invite more people to the project, as explained in [§51](http://www.zerocracy.com/policy.html#51)

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) everybody who has role `DEV` are banned at this job; I won't be able to assign anyone automatically; consider assigning someone manually or invite more people to the project, as explained in [§51](http://www.zerocracy.com/policy.html#51)

**Comment by yegor256** [comment]
@rultor release, tag is `0.19.4`

**Comment by 0crat** [comment]
The job [#57](https://github.com/yegor256/wring/issues/57) is now out of scope
