### ISSUE TITLE
java.util.concurrent.TimeoutException in Routine.call()

### ISSUE THREAD

**Issue by yegor256** [yegor256/wring#71]
```
2018-09-20T07:30:44.363587+00:00 app[web.1]: BUILD com.jcabi.log.VerboseRunnable: swallowed exception: java.lang.IllegalStateException: java.util.concurrent.TimeoutException
2018-09-20T07:30:44.363602+00:00 app[web.1]: at io.wring.agents.Routine.call(Routine.java:184)
2018-09-20T07:30:44.363606+00:00 app[web.1]: at com.jcabi.log.VerboseRunnable.run(VerboseRunnable.java:198)
2018-09-20T07:30:44.363604+00:00 app[web.1]: at io.wring.agents.Routine.lambda$start$0(Routine.java:129)
2018-09-20T07:30:44.363608+00:00 app[web.1]: at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
2018-09-20T07:30:44.363609+00:00 app[web.1]: at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
2018-09-20T07:30:44.363611+00:00 app[web.1]: at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
2018-09-20T07:30:44.363613+00:00 app[web.1]: at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
2018-09-20T07:30:44.363619+00:00 app[web.1]: at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
2018-09-20T07:30:44.363620+00:00 app[web.1]: at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
2018-09-20T07:30:44.363624+00:00 app[web.1]: at java.lang.Thread.run(Thread.java:748)
2018-09-20T07:30:44.363622+00:00 app[web.1]: at com.jcabi.log.VerboseThreads$Wrap.run(VerboseThreads.java:220)
2018-09-20T07:30:44.363626+00:00 app[web.1]: Caused by: java.util.concurrent.TimeoutException
2018-09-20T07:30:44.363629+00:00 app[web.1]: at io.wring.agents.Routine.call(Routine.java:181)
2018-09-20T07:30:44.363627+00:00 app[web.1]: at java.util.concurrent.FutureTask.get(FutureTask.java:205)
2018-09-20T07:30:44.363631+00:00 app[web.1]: ... 10 more
2018-09-20T07:30:44.363633+00:00 app[web.1]:
```

**Comment by 0crat** [comment]
@carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda) please, pay attention to this issue

**Comment by 0crat** [comment]
Job [#71](https://github.com/yegor256/wring/issues/71) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by 0crat** [comment]
Job [#71](https://github.com/yegor256/wring/issues/71) is already in scope

**Comment by 0crat** [comment]
@paulodamaso[/z](https://www.0crat.com/u/paulodamaso) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by paulodamaso** [comment]
@0crat refuse

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/yegor256/wring/issues/71#issuecomment-430338710))

@paulodamaso The user @paulodamaso[/z](https://www.0crat.com/u/paulodamaso) resigned from [#71](https://github.com/yegor256/wring/issues/71), please stop working. Reason for job resignation: Order was cancelled

**Comment by 0crat** [comment]
@carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda) everybody who has role `DEV` is banned at [#71](https://github.com/yegor256/wring/issues/71); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by 0crat** [comment]
Tasks refusal is discouraged, see [§6](http://www.zerocracy.com/policy.html#6): -15 point(s) just awarded to @paulodamaso[/z](https://www.0crat.com/u/paulodamaso)

**Comment by 0crat** [comment]
@carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda) everybody who has role `DEV` is banned at [#71](https://github.com/yegor256/wring/issues/71); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by 0crat** [comment]
@carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda) everybody who has role `DEV` is banned at [#71](https://github.com/yegor256/wring/issues/71); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by 0crat** [comment]
@carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda) everybody who has role `DEV` is banned at [#71](https://github.com/yegor256/wring/issues/71); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by 0crat** [comment]
@carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda) everybody who has role `DEV` is banned at [#71](https://github.com/yegor256/wring/issues/71); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by 0crat** [comment]
@carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda) everybody who has role `DEV` is banned at [#71](https://github.com/yegor256/wring/issues/71); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by 0crat** [comment]
@carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda) everybody who has role `DEV` is banned at [#71](https://github.com/yegor256/wring/issues/71); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by 0crat** [comment]
@carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda) everybody who has role `DEV` is banned at [#71](https://github.com/yegor256/wring/issues/71); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by 0crat** [comment]
@carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda) everybody who has role `DEV` is banned at [#71](https://github.com/yegor256/wring/issues/71); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))
