### ISSUE TITLE
wring could not start in netbeans

### ISSUE THREAD

**Issue by teyyub** [yegor256/wring#74]
Exception in thread "main" java.lang.IllegalArgumentException: Illegal character in path at index 1: ${sentry.dsn}
	at java.net.URI.create(URI.java:852)
	at io.sentry.dsn.Dsn.<init>(Dsn.java:40)
	at io.sentry.SentryClientFactory.resolveDsn(SentryClientFactory.java:73)
	at io.sentry.SentryClientFactory.sentryClient(SentryClientFactory.java:42)
	at io.sentry.Sentry.init(Sentry.java:81)
	at io.sentry.Sentry.init(Sentry.java:66)
	at io.wring.agents.Routine.start(Routine.java:109)
	at io.wring.Entrance.main(Entrance.java:64)

 
------------------------------------------------------------------------
BUILD FAILURE

**Comment by 0crat** [comment]
@carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda) please, pay attention to this issue

**Comment by 0crat** [comment]
@teyyub[/z](https://www.0crat.com/u/teyyub) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/C7FCB1EQN) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!
